/**
 * @file Automatically generated by barrelsby.
 */

export * from "./auth.controller";
export * from "./dashboard.controller";
export * from "./health.controller";
export * from "./result.controller";
export * from "./subject.controller";
export * from "./test.controller";
export * from "./user.controller";
